export const HERO_TITLE = " Full Stack Developer";

export const HERO_CONTENT = `I am a passionate full stack developer with a knack for crafting robust and scalable web applications. I have honed my skills in front-end technologies like React and Next.js, as well as back-end technologies like Java Spring Boot , Python, Oracle Database, MySQL, and also have a strong foundation in skills of Data Science. My goal is to leverage my expertise to create innovative solutions that drive business growth and deliver exceptional user experiences.`;

export const ABOUT_TEXT = `I am a dedicated and versatile full stack developer with a passion for creating efficient and user-friendly web applications. With a strong foundation in both front-end and back-end development, I have worked with a variety of technologies, My journey in web development began with a deep curiosity for how things work, and it has evolved into a career where I continuously strive to learn and adapt to new challenges. I thrive in collaborative environments and enjoy solving complex problems to deliver high-quality solutions. Outside of coding, I enjoy staying active, exploring new technologies, Travelling and contributing to open-source projects. Proficient in Core Java and J2EE (Java, Java Beans, Java Applets, Java Servlets) and web-based languages such as HTML, CSS, JavaScript, React, Bootstrap, Frameworks like Python Django and with a strong understanding of OOP concepts such as Inheritance and Polymorphism. Expertise in SQL and Oracle, including writing complex queries using Joins, Window functions, Constraints, Views, Indexes, Stored Procedures, and optimizing queries for performance. Experienced in Windows and Linux environments also developing CRUD operations and RESTful APIs and Agile Methodology Frameworks. Proficient in Data Structure and algorithms (DSA) like shorting, searching, and dynamic Programming, with a focus on transforming data into actionable insights and developing software application. Also Have Little bit of knowledge in Cloud deployment tools such as AWS.`;

export const CONTACT = {
  address: "Bhubaneswar, Odisha",
  phoneNo: "+91 1234567890",
  email: "vivekanandagiri@gmail.com",
};
